import React, { useMemo } from "react";
import { Paddle } from "./posting/paddle";
import { Component, useState } from "react";
import { Card, FormLabel, Button, Flex, FormControl, Heading, Input, Textarea } from "@chakra-ui/react";
import { useFireship } from "../hooks/useFireship";
import { Box } from "@chakra-ui/react";
import { useAuth } from "../contexts/AuthContext";
import { useHistory } from "react-router-dom";
import { useMusic } from "../hooks/useMusic";
export const Sounds = () => {};
